
[versions]
accompanistSwiperefresh = "0.36.0"
agp = "9.0.0"
coilComposeVersion = "3.3.0"
coreKtx = "1.17.0"
hiltCompiler = "2.59.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
ktorClientAndroidVersion = "3.4.0"
ktorClientCore = "3.4.0"
ktorUtils = "3.4.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
kotlin = "2.3.10"
composeBom = "2026.01.01"

postgrestKt = "3.3.0"
supabase = "3.3.0"
hiltAndroid = "2.59"
hiltNavigationCompose = "1.3.0"
devtoolsKsp = "2.0.20-1.0.25"
timber = "5.0.1"
datastorePreferences = "1.2.0"
googleServices = "4.4.4"
kotlinxSerializationJson = "1.10.0"
ktorClientAndroid = "3.4.0"
firebaseBom = "34.9.0"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
datastoreCore = "1.2.0"
ui = "1.10.2"
material3 = "1.4.0"
lifecycleViewmodelKtx = "2.10.0"
runtime = "1.10.2"
cameraCore = "1.5.3"
roomCommonJvm = "2.8.4"



[libraries]
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coil-compose-v330 = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilComposeVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroidVersion" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktorUtils" }
storage-kt = { module = "io.github.jan-tennert.supabase:storage-kt" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientAndroid" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
supabase-postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "postgrestKt" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
plugin-hilt = { id = "dagger.hilt.android.plugin", version.ref = "hiltAndroid" }
kapt-kotlin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }



